In [7]:
import plotly.express as px
import plotly.graph_objects as go

## Fetching the Data

In [4]:
df = px.data.gapminder().query("country == 'Canada'")
df.head()

    country continent  year  lifeExp       pop    gdpPercap iso_alpha  iso_num
240  Canada  Americas  1952    68.75  14785584  11367.16112       CAN      124
241  Canada  Americas  1957    69.96  17010154  12489.95006       CAN      124
242  Canada  Americas  1962    71.30  18985849  13462.48555       CAN      124
243  Canada  Americas  1967    72.13  20819767  16076.58803       CAN      124
244  Canada  Americas  1972    72.88  22284500  18970.57086       CAN      124

### Simple plotly graph

In [9]:
fig = px.line(df, x = 'year', 
              y = 'lifeExp', 
              title = "Life Expectancy in Canada",
              labels = {'lifeExp': 'Life Expectancy', 'year': 'Year'})

fig.show()

### Multiple lines Chart

In [10]:
df_stocks = px.data.stocks()
df_stocks.head()

         date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0  2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1  2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2  2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3  2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4  2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708

In [13]:
px.line(df_stocks,
        x = 'date',
        y = ['GOOG', 'AAPL'],
        labels = {'date': 'Date', 'value': 'Price'},
        title = 'Google vs Apple')

### With GO

In [16]:
fig = go.Figure()
fig.add_trace(go.Scatter(
    x = df_stocks.date,
    y = df_stocks.AAPL,
    mode = 'lines',
    name = 'Apple'
))