In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("Week1-Preprocessing1.csv")

In [6]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0

In [7]:
df.shape

(9450, 13)

In [ ]:
# Question 1
df.Price.mean()

np.float64(9027.895555555555)

In [ ]:
# Question 2
df.Month.unique()

array([6, 3, 5, 4])

In [10]:
df2 = df.groupby('Month').sum()
df2.Price.sort_values(ascending=False)

Month
5    28084275
6    27037541
3    23376720
4     6815077
Name: Price, dtype: int64

In [11]:
df.columns.to_list()

['Airline',
 'Source',
 'Destination',
 'Route',
 'Dep_Time',
 'Arrival_Time',
 'Duration',
 'Total_Stops',
 'Additional_Info',
 'Price',
 'Month',
 'WeekDay',
 'Day']

In [ ]:
# Question 3
# Week Day
week_day_df= df[df['WeekDay'].isin(['Thursday', 'Friday', 'Monday', 'Wednesday', 'Tuesday'])]
week_end_df = df[df['WeekDay'].isin(['Sunday', 'Saturday'])]

week_day_df.shape, week_end_df.shape

((6651, 13), (2799, 13))

In [13]:
week_day_df.Price.mean(), week_end_df.Price.mean()

(np.float64(9015.219666215608), np.float64(9058.016077170418))

In [40]:
df.replace("No Info", "No info", inplace=True)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,Duration in seconds,Dept_hour,Arrival_hour,Cat_dept_hour,Cat_arrival_hour,Cat_Week_Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0,95700,20,4,NaN,NaN,0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0,97200,16,19,Afternoon,Evening,1
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0,5400,19,21,Evening,NaN,0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0,54600,18,1,Evening,NaN,0
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0,30000,17,17,Evening,Evening,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9445,Air India,Banglore,Cochin,BLR → MAA → DEL,19:30,19:50,8h 55m,1 stop,In-flight meal not included,5932,6,Wednesday,12.0,32100,19,19,Evening,Evening,0
9446,IndiGo,Delhi,Cochin,DEL → BOM → COK,17:00,21:00,8h 35m,1 stop,No info,6838,3,Sunday,3.0,30900,17,21,Evening,NaN,1
9447,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,19:45,15h 15m,1 stop,No info,12615,3,Saturday,9.0,54900,7,19,Morning,Evening,1
9448,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,08:20,19:50,12h 5m,1 stop,No info,10844,5,Saturday,18.0,43500,8,19,Morning,Evening,1
9449,Air India,Kolkata,Banglore,CCU → GAU → IMF → DEL → BLR,14:30,23:15,8h 45m,3 stops,No info,15145,5,Thursday,9.0,31500,14,23,Afternoon,NaN,0

In [41]:
# Question 4
df.query('Airline == "IndiGo" and Additional_Info == "No info"')

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,Duration in seconds,Dept_hour,Arrival_hour,Cat_dept_hour,Cat_arrival_hour,Cat_Week_Day
8,IndiGo,Mumbai,Hyderabad,BOM → HYD,19:05,20:35,1h 30m,non-stop,No info,2754,5,Monday,6.0,5400,19,20,Evening,NaN,0
10,IndiGo,Delhi,Cochin,DEL → BOM → COK,09:00,01:30 10 May,10h,1 stop,No info,8854,6,Thursday,27.0,36000,9,1,Morning,NaN,0
12,IndiGo,Delhi,Cochin,DEL → BOM → COK,17:30,01:30 16 May,8h,1 stop,No info,6979,5,Wednesday,15.0,28800,17,1,Evening,NaN,0
18,IndiGo,Chennai,Banglore,MAA → CCU,16:40,14:00,7h 35m,non-stop,No info,3858,5,Monday,6.0,27300,16,14,Afternoon,Afternoon,0
35,IndiGo,Banglore,Delhi,BLR → DEL,22:10,01:00 22 May,2h 50m,non-stop,No info,3625,5,Tuesday,21.0,10200,22,1,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9425,IndiGo,Mumbai,Cochin,BOM → HYD,16:10,10:40,6h 10m,non-stop,No info,4575,3,Sunday,3.0,22200,16,10,Afternoon,Morning,1
9427,IndiGo,Chennai,Kolkata,MAA → CCU,22:05,00:25 10 May,2h 20m,non-stop,No info,5277,5,Thursday,9.0,8400,22,0,NaN,NaN,0
9429,IndiGo,Kolkata,Banglore,CCU → BLR,09:35,12:20,2h 45m,non-stop,No info,4462,3,Monday,18.0,9900,9,12,Morning,Afternoon,0
9438,IndiGo,Banglore,Delhi,BLR → DEL,04:00,06:50,2h 50m,non-stop,No info,3943,5,Friday,3.0,10200,4,6,NaN,Morning,0
9446,IndiGo,Delhi,Cochin,DEL → BOM → COK,17:00,21:00,8h 35m,1 stop,No info,6838,3,Sunday,3.0,30900,17,21,Evening,NaN,1

In [15]:
# Question 5
df.Duration.str.split().head(5)

0    [26h, 35m]
1         [27h]
2     [1h, 30m]
3    [15h, 10m]
4     [8h, 20m]
Name: Duration, dtype: object

In [16]:
def convert_to_seconds(row):
    '''
    This function will split the given time list into hours and minutes and return the time
    '''
    time_list = row['Duration'].split()
    total_seconds = 0
    
    # time is only in minutes or hours
    if len(time_list) == 1:
        if time_list[0][-1] == 'h':
            total_seconds += int(time_list[0][:-1])*60*60
        else: 
            total_seconds += int(time_list[0][:-1])*60
        return total_seconds
            
    else:    
        for ele in time_list:
            if ele[-1] == 'h':
                # an hour has 60 minutes, and 60 minutes have 60 seconds
                total_seconds += int(ele[:-1])*60*60
            else:
                # a minute has 60 seconds
                total_seconds += int(ele[:-1])*60
    return total_seconds

In [17]:
# add an hour column
df["Duration in seconds"] = df.apply(convert_to_seconds, axis = 1)

In [18]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,Duration in seconds
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0,95700
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0,97200
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0,5400
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0,54600
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0,30000

In [19]:
df["Duration in seconds"].mean()

np.float64(38957.93650793651)

In [20]:
# Question 6

def dept_hour(time):
    x = time.split(":")
    hour = int(x[0])
    return hour

def arrival_hour(obj):
    x = obj.split(":")
    hour = int(x[0])
    return hour

In [21]:
df["Dept_hour"] = df["Dep_Time"].apply(dept_hour)
df["Arrival_hour"] = df["Arrival_Time"].apply(arrival_hour)

In [22]:
def cat_hour(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 20:
        return "Evening"
    elif 20 <= hour < 5:
        return "Night"

In [31]:
df.sample()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,Duration in seconds,Dept_hour,Arrival_hour,Cat_dept_hour,Cat_arrival_hour
2137,GoAir,Banglore,Delhi,BLR → DEL,07:45,10:40,2h 55m,non-stop,No info,4239,5,Saturday,18.0,10500,7,10,Morning,Morning

In [26]:
df['Cat_dept_hour'] = df["Dept_hour"].apply(cat_hour)
df['Cat_arrival_hour'] = df["Arrival_hour"].apply(cat_hour)

In [32]:
df.query('Cat_dept_hour == "Morning" and Cat_arrival_hour == "Evening"')

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,Duration in seconds,Dept_hour,Arrival_hour,Cat_dept_hour,Cat_arrival_hour
15,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,7354,6,Wednesday,12.0,28200,11,19,Morning,Evening
39,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,05:45,19:10,13h 25m,1 stop,No info,16736,3,Wednesday,6.0,48300,5,19,Morning,Evening
48,Jet Airways,Delhi,Cochin,DEL → BOM → COK,11:30,19:00,7h 30m,1 stop,No info,14714,6,Wednesday,12.0,27000,11,19,Morning,Evening
49,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:30,19:00,11h 30m,1 stop,No info,9315,5,Thursday,9.0,41400,7,19,Morning,Evening
51,Air India,Delhi,Kolkata,DEL → CCU → BOM → COK,11:40,19:15 13 Jun,2h 15m,2 stops,No info,13381,3,Friday,1.0,8100,11,19,Morning,Evening
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9415,Jet Airways,Delhi,Cochin,DEL → BOM → COK,09:00,19:00,10h,1 stop,In-flight meal not included,10262,6,Saturday,15.0,36000,9,19,Morning,Evening
9432,Jet Airways,Mumbai,Banglore,BOM → HYD,11:35,17:20,7h 15m,non-stop,No info,2071,5,Monday,6.0,26100,11,17,Morning,Evening
9433,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,08:25,19:15,12h 15m,1 stop,In-flight meal not included,16108,3,Sunday,24.0,44100,8,19,Morning,Evening
9447,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,19:45,15h 15m,1 stop,No info,12615,3,Saturday,9.0,54900,7,19,Morning,Evening
9448,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,08:20,19:50,12h 5m,1 stop,No info,10844,5,Saturday,18.0,43500,8,19,Morning,Evening

In [33]:
# Question 7
def cat_weekday(day):
    if (day == "Saturday") or (day == "Sunday"):
        return 1
    else:
        return 0

In [34]:
df["Cat_Week_Day"] = df["WeekDay"].apply(cat_weekday)

In [38]:
df.sample(5)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,Duration in seconds,Dept_hour,Arrival_hour,Cat_dept_hour,Cat_arrival_hour,Cat_Week_Day
4648,Jet Airways,Delhi,Cochin,DEL → AMD → BOM → COK,10:35,12:35 10 May,9h,2 stops,No info,15129,5,Wednesday,15.0,32400,10,12,Morning,Afternoon,0
8112,Air India,Kolkata,Banglore,CCU → VNS → DEL → BLR,14:30,08:55 07 Jun,18h 25m,2 stops,No info,15107,6,Thursday,6.0,66300,14,8,Afternoon,Morning,0
5342,IndiGo,Banglore,New Delhi,BLR → DEL,21:20,00:15 02 Mar,2h 55m,non-stop,No info,12649,3,Friday,1.0,10500,21,0,NaN,NaN,0
5008,Vistara,Banglore,Delhi,BLR → DEL,17:00,19:35,2h 35m,non-stop,No info,4878,5,Saturday,18.0,9300,17,19,Evening,Evening,1
3711,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,08:00,19:15,13h,1 stop,No info,8099,5,Tuesday,21.0,46800,8,19,Morning,Evening,0

In [39]:
# Weekends are 1, else 0
df['Cat_Week_Day'].value_counts()

Cat_Week_Day
0    6651
1    2799
Name: count, dtype: int64