In [46]:
import pandas as pd
import numpy as np
from scipy import stats

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (
    StandardScaler, OneHotEncoder, OrdinalEncoder)

In [2]:
df = pd.read_csv('GA_2_dataset.csv')
df.head()

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
0,35900,37.0,Male,Other,Strategy,23.929404,NaN,Hard,3,124,99,18,Medium
1,27085,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12,Medium
2,39595,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18,Medium
3,37440,26.0,Female,Europe,RPG,11.009645,NaN,NaN,3,83,36,43,Low
4,22882,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24,Medium

In [3]:
df.shape

(10000, 13)

In [4]:
df = df.drop(columns = ['PlayerID'])

Question 1

In [5]:
df.dtypes

Age                          float64
Gender                        object
Location                      object
GameGenre                     object
PlayTimeHours                float64
InGamePurchases              float64
GameDifficulty                object
SessionsPerWeek                int64
AvgSessionDurationMinutes      int64
PlayerLevel                    int64
AchievementsUnlocked           int64
EngagementLevel               object
dtype: object

Question 2

In [6]:
df.query("Gender == 'Male' and InGamePurchases == 1 and Location == 'Europe'")

,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
30,26.0,Male,Europe,Action,23.347913,1.0,Medium,18,33,48,45,Medium
39,48.0,Male,Europe,Sports,8.759941,1.0,Medium,6,40,74,47,Medium
52,41.0,Male,Europe,Sports,8.683196,1.0,Hard,8,125,31,23,Medium
63,18.0,Male,Europe,Sports,17.287868,1.0,Easy,7,119,87,41,Medium
68,46.0,Male,Europe,Sports,12.306317,1.0,Medium,11,179,91,4,High
...,...,...,...,...,...,...,...,...,...,...,...,...
9880,33.0,Male,Europe,Sports,7.351962,1.0,Hard,8,95,36,5,Medium
9889,41.0,Male,Europe,Action,0.965662,1.0,Hard,17,104,32,33,High
9907,23.0,Male,Europe,RPG,9.154653,1.0,Hard,2,27,43,34,Low
9930,19.0,Male,Europe,RPG,7.825493,1.0,Easy,1,22,8,31,Low
9948,25.0,Male,Europe,Action,13.320361,1.0,Easy,16,45,5,0,Medium

Question 3

In [7]:
df.query("Age < 18 and PlayTimeHours > 10")

,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
25,15.0,Male,Asia,Sports,12.376600,0.0,Easy,2,100,49,43,High
64,16.0,Female,Europe,RPG,12.106891,0.0,Hard,1,85,78,4,Low
72,17.0,Female,Europe,Sports,18.473853,0.0,Easy,12,11,50,25,Low
133,17.0,Male,NaN,Strategy,23.178396,0.0,NaN,4,136,36,39,Medium
154,16.0,Female,USA,Sports,13.464307,0.0,Hard,3,26,20,12,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
9959,15.0,Male,Asia,Action,21.506080,0.0,Easy,15,132,35,34,High
9982,16.0,Male,USA,Simulation,11.236814,1.0,Easy,9,85,85,26,Medium
9984,15.0,Female,Europe,Strategy,16.071099,0.0,Easy,14,141,16,28,High
9987,17.0,Male,Asia,RPG,17.512651,0.0,Easy,14,84,36,18,Medium
9998,16.0,Male,Europe,Strategy,17.111949,0.0,Medium,6,70,24,32,Medium

In [8]:
df[(df['Age'] < 18) & (df["PlayTimeHours"] > 10)]

,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
25,15.0,Male,Asia,Sports,12.376600,0.0,Easy,2,100,49,43,High
64,16.0,Female,Europe,RPG,12.106891,0.0,Hard,1,85,78,4,Low
72,17.0,Female,Europe,Sports,18.473853,0.0,Easy,12,11,50,25,Low
133,17.0,Male,NaN,Strategy,23.178396,0.0,NaN,4,136,36,39,Medium
154,16.0,Female,USA,Sports,13.464307,0.0,Hard,3,26,20,12,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
9959,15.0,Male,Asia,Action,21.506080,0.0,Easy,15,132,35,34,High
9982,16.0,Male,USA,Simulation,11.236814,1.0,Easy,9,85,85,26,Medium
9984,15.0,Female,Europe,Strategy,16.071099,0.0,Easy,14,141,16,28,High
9987,17.0,Male,Asia,RPG,17.512651,0.0,Easy,14,84,36,18,Medium
9998,16.0,Male,Europe,Strategy,17.111949,0.0,Medium,6,70,24,32,Medium

Question 4

In [9]:
y = df[['EngagementLevel']]
y

     EngagementLevel
0             Medium
1             Medium
2             Medium
3                Low
4             Medium
...              ...
9995          Medium
9996             Low
9997          Medium
9998          Medium
9999          Medium

[10000 rows x 1 columns]

In [10]:
df.columns

Index(['Age', 'Gender', 'Location', 'GameGenre', 'PlayTimeHours',
       'InGamePurchases', 'GameDifficulty', 'SessionsPerWeek',
       'AvgSessionDurationMinutes', 'PlayerLevel', 'AchievementsUnlocked',
       'EngagementLevel'],
      dtype='object')

In [11]:
X = df[['Age', 'Gender', 'Location', 'GameGenre', 'PlayTimeHours', 'InGamePurchases', 'GameDifficulty', 'SessionsPerWeek', 'AvgSessionDurationMinutes', 'PlayerLevel', 'AchievementsUnlocked']]
X.head()

,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked
0,37.0,Male,Other,Strategy,23.929404,NaN,Hard,3,124,99,18
1,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12
2,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18
3,26.0,Female,Europe,RPG,11.009645,NaN,NaN,3,83,36,43
4,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24

In [12]:
X.isna().sum()

Age                          800
Gender                         0
Location                     798
GameGenre                      0
PlayTimeHours                  0
InGamePurchases              893
GameDifficulty               846
SessionsPerWeek                0
AvgSessionDurationMinutes      0
PlayerLevel                    0
AchievementsUnlocked           0
dtype: int64

In [13]:
X.isna().sum().sum()

np.int64(3337)

In [14]:
df.isna().sum().sum()

np.int64(3337)

Question 5

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size = 0.2,
    random_state = 42,
)

In [16]:
X_train.shape

(8000, 11)

In [17]:
y_train.value_counts().sort_values(ascending = False)

EngagementLevel
Medium             3983
Low                2021
High               1996
Name: count, dtype: int64

Question 6

In [18]:
X_train.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,7360.0,31.713995,9.934730,15.000000,23.000000,32.000000,40.000000,49.000000
PlayTimeHours,8000.0,12.033934,6.880316,0.002816,6.146341,11.982199,17.932587,23.997245
InGamePurchases,7284.0,0.199616,0.399739,0.000000,0.000000,0.000000,0.000000,1.000000
SessionsPerWeek,8000.0,9.471250,5.759021,0.000000,4.000000,9.000000,14.000000,19.000000
AvgSessionDurationMinutes,8000.0,95.231750,48.595048,10.000000,54.000000,95.000000,137.000000,179.000000
PlayerLevel,8000.0,49.540875,28.568621,1.000000,25.000000,49.000000,74.000000,99.000000
AchievementsUnlocked,8000.0,24.731375,14.395820,0.000000,12.000000,25.000000,37.000000,49.000000

In [19]:
X_train.describe(include = 'object').T

               count unique     top  freq
Gender          8000      2    Male  4874
Location        7361      4     USA  2935
GameGenre       8000      5  Sports  1621
GameDifficulty  7325      3    Easy  3660

Imputing age

In [20]:
X_train[['Age']].isna().sum(), X_test[['Age']].isna().sum()

(Age    640
 dtype: int64,
 Age    160
 dtype: int64)

In [21]:
age_imputer = SimpleImputer(strategy = 'mean')

age_imputer.fit(X_train[['Age']])

X_train[['Age']] = age_imputer.transform(X_train[['Age']])
X_test[['Age']] = age_imputer.transform(X_test[['Age']])

In [22]:
X_train[['Age']].isna().sum(), X_test[['Age']].isna().sum()

(Age    0
 dtype: int64,
 Age    0
 dtype: int64)

In [23]:
X_test['Age'].sum()

np.float64(63585.239130434784)

Imputing location

In [24]:
X_train[['Location']].isna().sum(), X_test[['Location']].isna().sum()

(Location    639
 dtype: int64,
 Location    159
 dtype: int64)

In [25]:
location_imputer = SimpleImputer(strategy = 'constant', fill_value = 'other')

location_imputer.fit(X_train[['Location']])

X_train[['Location']] = location_imputer.transform(X_train[['Location']])
X_test[['Location']] = location_imputer.transform(X_test[['Location']])

In [26]:
X_train[['Location']].isna().sum(), X_test[['Location']].isna().sum()

(Location    0
 dtype: int64,
 Location    0
 dtype: int64)

Imputing Game Difficulty

In [27]:
X_train[['GameDifficulty']].isna().sum(), X_test[['GameDifficulty']].isna().sum()

(GameDifficulty    675
 dtype: int64,
 GameDifficulty    171
 dtype: int64)

In [28]:
difficulty_imputer = SimpleImputer(strategy = 'most_frequent')

difficulty_imputer.fit(X_train[['GameDifficulty']])

X_train[['GameDifficulty']] = difficulty_imputer.transform(X_train[['GameDifficulty']])
X_test[['GameDifficulty']] = difficulty_imputer.transform(X_test[['GameDifficulty']])

In [29]:
X_train[['GameDifficulty']].isna().sum(), X_test[['GameDifficulty']].isna().sum()

(GameDifficulty    0
 dtype: int64,
 GameDifficulty    0
 dtype: int64)

Imputing Purchases

In [30]:
X_train[['InGamePurchases']].isna().sum(), X_test[['InGamePurchases']].isna().sum()

(InGamePurchases    716
 dtype: int64,
 InGamePurchases    177
 dtype: int64)

In [31]:
purchase_imputer = SimpleImputer(strategy = 'constant', fill_value = 0)

purchase_imputer.fit(X_train[['InGamePurchases']])

X_train[['InGamePurchases']] = purchase_imputer.transform(X_train[['InGamePurchases']])
X_test[['InGamePurchases']] = purchase_imputer.transform(X_test[['InGamePurchases']])

In [32]:
X_train[['InGamePurchases']].isna().sum(), X_test[['InGamePurchases']].isna().sum()

(InGamePurchases    0
 dtype: int64,
 InGamePurchases    0
 dtype: int64)

Question 7

In [33]:
X_train.columns

Index(['Age', 'Gender', 'Location', 'GameGenre', 'PlayTimeHours',
       'InGamePurchases', 'GameDifficulty', 'SessionsPerWeek',
       'AvgSessionDurationMinutes', 'PlayerLevel', 'AchievementsUnlocked'],
      dtype='object')

In [35]:
gender_ohe = OneHotEncoder(drop = 'first', sparse_output = False)

gender_ohe.fit(X_train[['Gender', 'Location', 'GameGenre']])

nominal_features_train = pd.DataFrame(gender_ohe.transform(X_train[['Gender', 'Location', 'GameGenre']]), columns=gender_ohe.get_feature_names_out())
nominal_features_test = pd.DataFrame(gender_ohe.transform(X_test[['Gender', 'Location', 'GameGenre']]), columns=gender_ohe.get_feature_names_out())
# nominal_features_train = pd.DataFrame(gender_ohe.transform(X_train[['Gender', 'Location', 'GameGenre']]).toarray(), columns=gender_ohe.get_feature_names_out())
# nominal_features_test = pd.DataFrame(gender_ohe.transform(X_test[['Gender', 'Location', 'GameGenre']]).toarray(), columns=gender_ohe.get_feature_names_out())

X_train.drop(columns = ['Gender', 'Location', 'GameGenre'], inplace = True)
X_test.drop(columns = ['Gender', 'Location', 'GameGenre'], inplace = True)

In [ ]:
gender_ohe.get_feature_names_out()

array(['Gender_Male', 'Location_Europe', 'Location_Other', 'Location_USA',
       'Location_other', 'GameGenre_RPG', 'GameGenre_Simulation',
       'GameGenre_Sports', 'GameGenre_Strategy'], dtype=object)

In [37]:
X_train = pd.concat([X_train.reset_index(), nominal_features_train.reset_index()], axis = 1)
X_test = pd.concat([X_test.reset_index(), nominal_features_test.reset_index()], axis = 1)
X_train.head()

,index,Age,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,index,Gender_Male,Location_Europe,Location_Other,Location_USA,Location_other,GameGenre_RPG,GameGenre_Simulation,GameGenre_Sports,GameGenre_Strategy
0,9254,34.0,15.777862,0.0,Medium,5,76,80,33,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1561,41.0,3.044182,0.0,Medium,7,73,34,5,1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,1670,48.0,0.585613,0.0,Medium,16,163,44,3,2,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,6087,19.0,6.194149,0.0,Easy,6,87,26,33,3,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6669,38.0,21.610488,0.0,Easy,14,116,39,14,4,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [38]:
oe = OrdinalEncoder()

oe.fit(X_train[['GameDifficulty']])

X_train[['GameDifficulty']] = oe.transform(X_train[['GameDifficulty']])
X_test[['GameDifficulty']] = oe.transform(X_test[['GameDifficulty']])

In [39]:
X_train.head()

,index,Age,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,index,Gender_Male,Location_Europe,Location_Other,Location_USA,Location_other,GameGenre_RPG,GameGenre_Simulation,GameGenre_Sports,GameGenre_Strategy
0,9254,34.0,15.777862,0.0,2.0,5,76,80,33,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1561,41.0,3.044182,0.0,2.0,7,73,34,5,1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,1670,48.0,0.585613,0.0,2.0,16,163,44,3,2,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,6087,19.0,6.194149,0.0,0.0,6,87,26,33,3,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6669,38.0,21.610488,0.0,0.0,14,116,39,14,4,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [40]:
X_test.columns

Index(['index', 'Age', 'PlayTimeHours', 'InGamePurchases', 'GameDifficulty',
       'SessionsPerWeek', 'AvgSessionDurationMinutes', 'PlayerLevel',
       'AchievementsUnlocked', 'index', 'Gender_Male', 'Location_Europe',
       'Location_Other', 'Location_USA', 'Location_other', 'GameGenre_RPG',
       'GameGenre_Simulation', 'GameGenre_Sports', 'GameGenre_Strategy'],
      dtype='object')

In [41]:
scaler = StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [45]:
X_test[:5].sum()

np.float64(-14.907352846784795)