In [1]:
import pandas as pd

In [ ]:
rainfall_df = pd.read_csv('daily-rainfall-at-state-level.csv') # we will filter out only rajasthan

In [ ]:
power_df = pd.read_csv('long_data_.csv') # we will filter out only rajasthan

In [ ]:
heatwave_df = pd.read_csv('Rajasthan_Heatwave_2006_2025.csv') # already has all rajasthan data

In [ ]:
climate_df = pd.read_csv('india_climate_2000_2025.csv') # we will filter out only rajasthan

### Exploring DataFrames

#### Rainfall DataFrame

In [9]:
rainfall_df.columns

Index(['id', 'date', 'state_code', 'state_name', 'actual', 'rfs', 'normal',
       'deviation'],
      dtype='object')

In [10]:
rainfall_df.head()

,id,date,state_code,state_name,actual,rfs,normal,deviation
0,0,2009-01-01,5,Uttarakhand,0.0,0.003906,2.19,-100.0
1,1,2009-01-01,18,Assam,0.0,0.000000,0.52,-100.0
2,2,2009-01-01,16,Tripura,0.0,0.000000,0.09,-100.0
3,3,2009-01-01,36,Telangana,0.0,0.000000,0.17,-100.0
4,4,2009-01-01,2,Himachal Pradesh,0.0,0.008566,3.31,-100.0

In [14]:
rainfall_df.state_name.value_counts()

state_name
Uttarakhand                                     5691
Assam                                           5691
Tripura                                         5691
Telangana                                       5691
Himachal Pradesh                                5691
Jammu And Kashmir                               5691
Meghalaya                                       5691
Lakshadweep                                     5691
Maharashtra                                     5691
Punjab                                          5691
Jharkhand                                       5691
Andhra Pradesh                                  5691
Arunachal Pradesh                               5691
Ladakh                                          5691
Andaman And Nicobar Islands                     5691
Goa                                             5691
Uttar Pradesh                                   5691
Haryana                                         5691
Madhya Pradesh                                  5691
Manipur                                         5691
Karnataka                                       5691
Chandigarh                                      5691
West Bengal                                     5691
Rajasthan                                       5691
Chhattisgarh                                    5691
Nagaland                                        5691
Bihar                                           5691
Puducherry                                      5691
Gujarat                                         5691
Odisha                                          5691
Tamil Nadu                                      5691
Kerala                                          5691
Sikkim                                          5691
Delhi                                           5691
Mizoram                                         5691
The Dadra And Nagar Haveli And Daman And Diu    5691
Name: count, dtype: int64

In [18]:
rainfall_df.query("state_name == 'Rajasthan'")

,id,date,state_code,state_name,actual,rfs,normal,deviation
23,23,2009-01-01,8,Rajasthan,0.00,0.010813,0.15,-100.00
58,58,2009-01-02,8,Rajasthan,0.00,0.000000,0.15,-100.00
93,93,2009-01-03,8,Rajasthan,0.01,0.114927,0.16,-93.75
128,128,2009-01-04,8,Rajasthan,0.00,0.033657,0.15,-100.00
163,163,2009-01-05,8,Rajasthan,0.03,0.368454,0.28,-89.29
...,...,...,...,...,...,...,...,...
199033,199033,2024-07-27,8,Rajasthan,NaN,0.000000,5.80,NaN
199068,199068,2024-07-28,8,Rajasthan,NaN,0.000000,4.77,NaN
199103,199103,2024-07-29,8,Rajasthan,NaN,0.000000,4.76,NaN
199138,199138,2024-07-30,8,Rajasthan,NaN,0.000000,4.69,NaN
199173,199173,2024-07-31,8,Rajasthan,NaN,0.000000,4.56,NaN

In [ ]:
# converting to datetime
pd.to_datetime(rainfall_df['date'], errors = 'coerce')

0        2009-01-01
1        2009-01-01
2        2009-01-01
3        2009-01-01
4        2009-01-01
            ...
204871   2024-07-27
204872   2024-07-28
204873   2024-07-29
204874   2024-07-30
204875   2024-07-31
Name: date, Length: 204876, dtype: datetime64[ns]

In [37]:
rainfall_df.date.min(), rainfall_df.date.max()

('2009-01-01', '2024-07-31')

#### Power DataFrame

In [19]:
power_df.columns

Index(['States', 'Regions', 'latitude', 'longitude', 'Dates', 'Usage'], dtype='object')

In [22]:
power_df.States.value_counts()

States
Punjab               503
Haryana              503
Rajasthan            503
Delhi                503
UP                   503
Uttarakhand          503
HP                   503
J&K                  503
Chandigarh           503
Chhattisgarh         503
Gujarat              503
MP                   503
Maharashtra          503
Goa                  503
DNH                  503
Andhra Pradesh       503
Telangana            503
Karnataka            503
Kerala               503
Tamil Nadu           503
Pondy                503
Bihar                503
Jharkhand            503
Odisha               503
West Bengal          503
Sikkim               503
Arunachal Pradesh    503
Assam                503
Manipur              503
Meghalaya            503
Mizoram              503
Nagaland             503
Tripura              503
Name: count, dtype: int64

In [23]:
power_df.query("States == 'Rajasthan'")

          States Regions   latitude  longitude                Dates  Usage
2      Rajasthan      NR  26.449999  74.639981  02/01/2019 00:00:00  234.1
35     Rajasthan      NR  26.449999  74.639981  03/01/2019 00:00:00  240.2
68     Rajasthan      NR  26.449999  74.639981  04/01/2019 00:00:00  239.8
101    Rajasthan      NR  26.449999  74.639981  05/01/2019 00:00:00  239.1
134    Rajasthan      NR  26.449999  74.639981  06/01/2019 00:00:00  240.4
...          ...     ...        ...        ...                  ...    ...
16436  Rajasthan      NR  26.449999  74.639981  01/12/2020 00:00:00  220.4
16469  Rajasthan      NR  26.449999  74.639981  02/12/2020 00:00:00  218.4
16502  Rajasthan      NR  26.449999  74.639981  03/12/2020 00:00:00  205.6
16535  Rajasthan      NR  26.449999  74.639981  04/12/2020 00:00:00  207.0
16568  Rajasthan      NR  26.449999  74.639981  05/12/2020 00:00:00  201.4

[503 rows x 6 columns]

In [ ]:
# converting to datetime
pd.to_datetime(power_df['Dates'], errors = 'coerce')

0       2019-02-01
1       2019-02-01
2       2019-02-01
3       2019-02-01
4       2019-02-01
           ...
16594   2020-05-12
16595   2020-05-12
16596   2020-05-12
16597   2020-05-12
16598   2020-05-12
Name: Dates, Length: 16599, dtype: datetime64[ns]

In [35]:
power_df.Dates.min(), power_df.Dates.max()

('01/01/2020 00:00:00', '31/12/2019 00:00:00')

#### Climate DataFrame

In [24]:
climate_df.columns

Index(['year', 'month', 'season', 'state', 'region', 'avg_temp_c',
       'max_temp_c', 'min_temp_c', 'rainfall_mm', 'humidity_pct',
       'wind_speed_kmh', 'sunshine_hrs', 'heat_index', 'temp_anomaly_c',
       'el_nino_flag', 'drought_flag'],
      dtype='object')

In [25]:
climate_df.state.value_counts()

state
Assam             312
Gujarat           312
Kerala            312
Madhya Pradesh    312
Maharashtra       312
Odisha            312
Punjab            312
Rajasthan         312
Tamil Nadu        312
West Bengal       312
Name: count, dtype: int64

In [26]:
climate_df.query("state == 'Rajasthan'")

,year,month,season,state,region,avg_temp_c,max_temp_c,min_temp_c,rainfall_mm,humidity_pct,wind_speed_kmh,sunshine_hrs,heat_index,temp_anomaly_c,el_nino_flag,drought_flag
2184,2000,1,Winter,Rajasthan,North,15.79,28.85,2.35,0.03,27.94,7.42,4.00,25.30,0.62,0,1
2185,2000,2,Winter,Rajasthan,North,16.08,35.11,4.93,0.20,27.39,7.02,5.37,25.04,-2.40,0,0
2186,2000,3,Summer,Rajasthan,North,22.63,39.20,9.06,0.03,15.09,7.96,6.54,23.44,-2.05,0,1
2187,2000,4,Summer,Rajasthan,North,31.42,43.85,17.15,0.01,13.79,10.37,7.34,29.28,0.86,0,1
2188,2000,5,Summer,Rajasthan,North,34.84,44.59,23.55,0.62,28.22,14.76,7.02,34.10,0.60,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2491,2025,8,Monsoon,Rajasthan,North,28.38,34.75,23.62,6.03,78.33,9.72,5.06,32.78,-1.95,0,0
2492,2025,9,Monsoon,Rajasthan,North,27.17,34.85,20.72,3.53,79.00,8.32,5.43,30.02,-2.79,0,0
2493,2025,10,Post-Monsoon,Rajasthan,North,23.94,33.16,15.99,1.42,64.72,5.69,4.58,25.09,-3.16,0,0
2494,2025,11,Post-Monsoon,Rajasthan,North,19.35,31.23,9.47,0.27,49.57,4.97,4.16,25.45,-2.28,0,0
2495,2025,12,Winter,Rajasthan,North,17.36,28.78,7.21,0.03,40.09,4.79,3.86,26.37,0.41,0,1

In [42]:
climate_df.year.min(), climate_df.year.max()

(np.int64(2000), np.int64(2025))

#### Heatwave DataFrame

In [38]:
heatwave_df.columns

Index(['YEAR', 'MONTH', 'DAY', 'WIND_U10', 'WIND_V10', 'MSLP', 'BLH', 'GEOP',
       'TEMP2M', 'TMAX', 'TMIN', 'DEW2M', 'CLOUD', 'RAIN', 'SRAD', 'EVAP',
       'SOILT1', 'SOILM1', 'LAI', 'HEATWAVE', 'LAT', 'LON', 'DISTRICT'],
      dtype='object')

In [39]:
heatwave_df.head()

,YEAR,MONTH,DAY,WIND_U10,WIND_V10,MSLP,BLH,GEOP,TEMP2M,TMAX,...,RAIN,SRAD,EVAP,SOILT1,SOILM1,LAI,HEATWAVE,LAT,LON,DISTRICT
0,2006,3,1,-0.223022,-0.440903,101036.375,2020.7317,1671.1079,304.75806,303.54395,...,0.0,3117056,-0.000023,312.75903,0.024887,0.515625,0,25.75,71.5,Barmer
1,2006,3,2,-1.344009,-0.294922,101076.440,2265.7910,1671.1079,306.45337,304.95703,...,0.0,3131200,-0.000024,312.66943,0.024345,0.515625,0,25.75,71.5,Barmer
2,2006,3,3,-0.960449,1.522965,101033.750,3152.6023,1671.1079,307.34863,306.21167,...,0.0,3105536,-0.000024,313.12280,0.023773,0.515625,0,25.75,71.5,Barmer
3,2006,3,4,2.704514,1.733017,100896.940,3146.9475,1671.1079,307.43457,306.70508,...,0.0,3126528,-0.000024,314.12085,0.023147,0.515625,0,25.75,71.5,Barmer
4,2006,3,5,2.717834,2.464432,101014.190,2069.5261,1671.1079,306.19507,304.88306,...,0.0,2776448,-0.000041,312.00806,0.027964,0.515625,0,25.75,71.5,Barmer

In [41]:
heatwave_df.YEAR.min(), heatwave_df.YEAR.max()

(np.int64(2006), np.int64(2025))